### ISSUE TITLE
Shows Users outside my Domain

### ISSUE THREAD

**Issue by jan-zat** [lcannatti/bns-user-identify#3]
In the list I can also see the private Accounts of some of my employees with their @googlemail.com Account and some Externals. It also shows "undefined".
What does this mean?

**Comment by lcannatti** [comment]
Thanks for raising this, the external emails will be there if they've modified files owned by your domain. The undefined entries are likely from deleted accounts, but probably aren't relevant to administration, so applying a fix to skip over these entries in the list generation process.
