### ISSUE TITLE
Error: Debug info: {"name":"ScriptError"}

### ISSUE THREAD

**Issue by Agiomir** [lcannatti/bns-user-identify#4]
Hello, we receive this error:

The script encountered an error. Please try again later. Debug info: {"name":"ScriptError"}

Any idea?

Thank you

**Comment by lcannatti** [comment]
Are you able to see any errors in your execution log for the project?

**Comment by Agiomir** [comment]
Hello @lcannatti sorry for the delay reply. Find below the error from log:
Error	TypeError: Cannot read property 'length' of undefined at pullSegment(Code:20:25)

**Comment by Agiomir** [comment]
Hello @lcannatti 
After updating the code, issue resolved.
