### ISSUE TITLE
Completed with no error

### ISSUE THREAD

**Issue by luca76pc** [lcannatti/bns-user-identify#7]
Current version completes without exceptions in log.
But there is no result shown in the html page.
I waited for a couple of minutes after"Loading..." label disappears but nothing happened.
Dig into it, please.

**Comment by lcannatti** [comment]
Hi Luca,
Commit [#9298b0a](https://github.com/lcannatti/bns-user-identify/commit/9298b0a70eac975ab3c07ce9578e9fb80003f482) should have resolved this as reported in issue #5. 
First I'd recommend updating the index.html file in your project and re-deploying the project.
If that doesn't resolve it, can you check your javascript console for errors and share any you find here?
Thanks!

**Comment by luca76pc** [comment]
Hi,
redeployed and run.
IMHO not resolved, because there is no message at the end.
In JS console I read two messages from https://script.google.com/static/macros/client/js/3328590226-warden_bin_i18n_warden__it.js:
- Net state changed from IDLE to BUSY
- Net state changed from BUSY to IDLE

I keep on trying...

**Comment by lcannatti** [comment]
Can you share the output of the following command in the js console while in the deployed webapp:

document.querySelector('body script').outerHTML

**Comment by lcannatti** [comment]
closing as this has been inactive for a month. Will reopen if the requested data is available.
